### ISSUE TITLE
Usage without composer

### ISSUE THREAD

**Issue by daun** [hirasso/wp-sync-deploy#1]
Love it! Can I use this without composer? My customer insists on potato hosting and they also don't have wp-cli :)

**Comment by hirasso** [comment]
Glad you asked! wp-sync-deploy was actually build with potato hosting in mind 🥔😄 All you need is an SSH connection. 

The script will then take care of installing wp-cli itself. Also, a hoster without composer installed is no issue as the script will simply deploy your local files, including your installed composer dependencies if you tell it to do so.

**Comment by daun** [comment]
Sounds great! Will give it a spin, then 🌝
